blueprint:
  name: Optimale batterij lading voor zonsondergang
  description: Stelt de batterij laadsnelheid in op basis van de resterende zonneopbrengst om de batterij volledig op te laden 2 uur voor zonsondergang. Begrensd op maximaal 5000W.
  domain: automation
  input:
    battery_state_of_charge:
      name: Batterij laadniveau sensor
      selector:
        entity:
          integration: sensor
    solcast_remaining_today:
      name: Solcast resterende opbrengst sensor
      selector:
        entity:
          integration: sensor
    battery_capacity:
      name: Batterij capaciteit (kWh)
      selector:
        number:
          min: 0
          mode: box
    battery_min_charging_power:
      name: Minimale laadsnelheid (W)
      selector:
        number:
          min: 0
          mode: box
    battery_max_charging_power:
      name: Maximale laadsnelheid (W)
      selector:
        number:
          min: 0
          mode: box
    battery_charging_power:
      name: Huidige laadsnelheid (W)
      selector:
        number:
          min: 0
          mode: box

trigger:
  platform: state
  entity_id: !input solcast_remaining_today

variables:
  battery_state_of_charge: "{{ states(trigger.entity_id.split('.')[1]) }}"
  solcast_remaining_today: "{{ trigger.to_state.state }}"
  battery_capacity: !input battery_capacity
  doel_tijd: "{{ (as_timestamp(sun.next_setting('astronomical_twilight_end')) - 7200) }}"
  resterende_lading: "{{ battery_capacity - battery_state_of_charge }}"
  vereiste_snelheid: "{{ min(resterende_lading / solcast_remaining_today, battery_max_charging_power | float) }}"
  laadsnelheid: "{{ max(vereiste_snelheid, battery_min_charging_power | float) }}"

action:
  - service: input_number.set_value
    target:
      entity_id: !input battery_charging_power
    data:
      value: "{{ laadsnelheid }}"
